-- MySQL Script generated by MySQL Workbench
-- 01/21/17 10:36:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mercadorias_valemobi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mercadorias_valemobi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mercadorias_valemobi` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mercadorias_valemobi` ;

-- -----------------------------------------------------
-- Table `mercadorias_valemobi`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadorias_valemobi`.`categoria` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idclientes_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mercadorias_valemobi`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadorias_valemobi`.`produto` (
  `codigo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `quantidade` INT NOT NULL,
  `preco` DOUBLE NOT NULL,
  `tipo_negocio` VARCHAR(7) NOT NULL,
  `categoria_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `idmercadorias_UNIQUE` (`codigo` ASC),
  INDEX `fk_produto_categoria_idx` (`categoria_id` ASC),
  CONSTRAINT `fk_produto_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `mercadorias_valemobi`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
